// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_char int8

type _Ctype_int int32

type _Ctype_person = _Ctype_struct_person

type _Ctype_struct_person struct {
	name	*_Ctype_char
	score1	_Ctype_int
	score2	_Ctype_int
}

type _Ctype_ulong uint64

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgo_runtime_cgocallback runtime.cgocallback
func _cgo_runtime_cgocallback(unsafe.Pointer, unsafe.Pointer, uintptr, uintptr)

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})
const _Ciconst_sizeof_struct_person = 0x10

//go:cgo_import_static _cgo_cd21771de9c2_Cfunc_get_person
//go:linkname __cgofn__cgo_cd21771de9c2_Cfunc_get_person _cgo_cd21771de9c2_Cfunc_get_person
var __cgofn__cgo_cd21771de9c2_Cfunc_get_person byte
var _cgo_cd21771de9c2_Cfunc_get_person = unsafe.Pointer(&__cgofn__cgo_cd21771de9c2_Cfunc_get_person)

//go:cgo_unsafe_args
func _Cfunc_get_person() (r1 _Ctype_struct_person) {
	_cgo_runtime_cgocall(_cgo_cd21771de9c2_Cfunc_get_person, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_cd21771de9c2_Cfunc_sum
//go:linkname __cgofn__cgo_cd21771de9c2_Cfunc_sum _cgo_cd21771de9c2_Cfunc_sum
var __cgofn__cgo_cd21771de9c2_Cfunc_sum byte
var _cgo_cd21771de9c2_Cfunc_sum = unsafe.Pointer(&__cgofn__cgo_cd21771de9c2_Cfunc_sum)

//go:cgo_unsafe_args
func _Cfunc_sum(p0 _Ctype_int, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_cd21771de9c2_Cfunc_sum, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
