// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

/*
typedef struct person {
	char* name;
	int score1;
	int score2;
} person;

person get_person() {
	person zy;
	zy.name = "zouying";
	zy.score1 = 100;
	zy.score2 = 100;

	return zy;
}

int sum(int a, int b) { return a+b; }
*/
import _ "unsafe"

import "log"

func SayHello() { println("hello ZOUYING") }

func main() {

	SayHello()

	p := ( /*line :31:7*/_Cfunc_get_person /*line :31:18*/)()
	log.Printf("%#v, size of person: %d", p, ( /*line :32:43*/_Ciconst_sizeof_struct_person /*line :32:64*/))

	value := ( /*line :34:11*/_Cfunc_sum /*line :34:15*/)(p.score1, p.score2)
	println("score=", value)
}
